### ISSUE TITLE
Paper Server, Game Rules still not working in 2.2.1.

### ISSUE THREAD

**Issue by CodingAlphaWolf** [Mathildeuh/WorldManager#16]
After wanting to edit the gamerules via the gui of my world Heist:

[01:08:41 ERROR]: [WorldManager] Exception while handling click event in inventory 'Options for Heist', slot=3, item=COMMAND_BLOCK
java.lang.NoSuchMethodError: 'net.kyori.adventure.key.Key org.bukkit.GameRule.key()'
	at WorldManager-2.2.1.jar/fr.mathildeuh.worldmanager.guis.GameRuleEditorGUI.createGameRuleGui(GameRuleEditorGUI.java:103) ~[WorldManager-2.2.1.jar:?]
	at WorldManager-2.2.1.jar/fr.mathildeuh.worldmanager.guis.GameRuleEditorGUI.getGui(GameRuleEditorGUI.java:67) ~[WorldManager-2.2.1.jar:?]
	at WorldManager-2.2.1.jar/fr.mathildeuh.worldmanager.guis.EditorOptionsGUI.lambda$createGui$1(EditorOptionsGUI.java:45) ~[WorldManager-2.2.1.jar:?]
	at WorldManager-2.2.1.jar/fr.mathildeuh.inventoryframework.gui.GuiItem.callAction(GuiItem.java:179) ~[WorldManager-2.2.1.jar:?]
	at WorldManager-2.2.1.jar/fr.mathildeuh.inventoryframework.pane.StaticPane.click(StaticPane.java:238) ~[WorldManager-2.2.1.jar:?]
	at WorldManager-2.2.1.jar/fr.mathildeuh.inventoryframework.gui.InventoryComponent.click(InventoryComponent.java:205) ~[WorldManager-2.2.1.jar:?]
	at WorldManager-2.2.1.jar/fr.mathildeuh.inventoryframework.gui.type.ChestGui.click(ChestGui.java:161) ~[WorldManager-2.2.1.jar:?]
	at WorldManager-2.2.1.jar/fr.mathildeuh.inventoryframework.gui.GuiListener.onInventoryClick(GuiListener.java:82) ~[WorldManager-2.2.1.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor251.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:84) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:1.21.1-17-fb53074]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.1.jar:1.21.1-17-fb53074]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.1.jar:1.21.1-17-fb53074]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3189) ~[paper-1.21.1.jar:1.21.1-17-fb53074]
	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:69) ~[paper-1.21.1.jar:1.21.1-17-fb53074]
	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:33) ~[paper-1.21.1.jar:1.21.1-17-fb53074]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56) ~[paper-1.21.1.jar:1.21.1-17-fb53074]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.21.1.jar:1.21.1-17-fb53074]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-1.21.1.jar:1.21.1-17-fb53074]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.21.1.jar:1.21.1-17-fb53074]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1537) ~[paper-1.21.1.jar:1.21.1-17-fb53074]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[paper-1.21.1.jar:1.21.1-17-fb53074]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[paper-1.21.1.jar:1.21.1-17-fb53074]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1514) ~[paper-1.21.1.jar:1.21.1-17-fb53074]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1507) ~[paper-1.21.1.jar:1.21.1-17-fb53074]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[paper-1.21.1.jar:1.21.1-17-fb53074]
	at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1466) ~[paper-1.21.1.jar:1.21.1-17-fb53074]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1473) ~[paper-1.21.1.jar:1.21.1-17-fb53074]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1318) ~[paper-1.21.1.jar:1.21.1-17-fb53074]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.1.jar:1.21.1-17-fb53074]
	at java.base/java.lang.Thread.run(Unknown Source) ~[?:?]
>

**Comment by Mathildeuh** [comment]
Hi, where did you download the plugin from? Use the latest version: https://github.com/Mathildeuh/WorldManager/releases/download/4.0.0/WorldManager-4.0.0.jar

**Comment by CodingAlphaWolf** [comment]
I downloaded this one from modrinth.

**Comment by Mathildeuh** [comment]
You can update it, idk how you download this version

**Comment by CodingAlphaWolf** [comment]
modrinth told me it was the latest. Thanks for your help I'll try the new updated version. sorry to bother you!

**Comment by CodingAlphaWolf** [comment]
its fixed!
